name: overlandAmerica
favicon: null
layout_spectrum: 0.00718
typography_spectrum: 0.47218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdfffc'
    - '#555f69'
    - '#0a0d12'
    - '#7699c1'
    - '#e1ae75'
  brandStrength: 0.5
  lightness: 0.25913577782921493
  saturation: 0.150701706064865
  rhythmicContrast: 0.11658830079250038
purpose: []
